package lab8_eliasgiron;

import java.io.IOException;
import java.util.ArrayList;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.JProgressBar;

/**
 *
 * @author EliasGZ
 */
public class Interfaz extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
        ah = new administrarHack(pgb_regular);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_super = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jl_super = new javax.swing.JList<>();
        jb_simulacion = new javax.swing.JButton();
        jb_agregar = new javax.swing.JButton();
        pgb_super = new javax.swing.JProgressBar();
        jb_abrir = new javax.swing.JButton();
        cb_hacks = new javax.swing.JComboBox<>();
        jd_regular = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        jb_agregarregular = new javax.swing.JButton();
        jb_simular = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jl_regulares = new javax.swing.JList<>();
        pgb_regular = new javax.swing.JProgressBar();
        jb_abrir2 = new javax.swing.JButton();
        cb_regular = new javax.swing.JComboBox<>();
        jd_agregarhack = new javax.swing.JDialog();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jb_guardarhack = new javax.swing.JButton();
        tf_codigo = new javax.swing.JTextField();
        Riesgo = new javax.swing.JLabel();
        tf_riesgo = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jb_hackregular = new javax.swing.JButton();
        jb_superhack = new javax.swing.JButton();

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        jl_super.setModel(new DefaultListModel());
        jl_super.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jl_superMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jl_super);

        jb_simulacion.setText("Simular Hackeo");
        jb_simulacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_simulacionMouseClicked(evt);
            }
        });

        jb_agregar.setText("Agregar");
        jb_agregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_agregarMouseClicked(evt);
            }
        });

        jb_abrir.setText("Abrir Archivo");
        jb_abrir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_abrirMouseClicked(evt);
            }
        });

        cb_hacks.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_hacksItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(cb_hacks, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(22, 22, 22)
                            .addComponent(jb_simulacion)
                            .addGap(18, 18, 18)
                            .addComponent(jb_agregar)
                            .addGap(18, 18, 18)
                            .addComponent(jb_abrir))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(39, 39, 39)
                            .addComponent(pgb_super, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(cb_hacks, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_simulacion)
                    .addComponent(jb_agregar)
                    .addComponent(jb_abrir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(pgb_super, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout jd_superLayout = new javax.swing.GroupLayout(jd_super.getContentPane());
        jd_super.getContentPane().setLayout(jd_superLayout);
        jd_superLayout.setHorizontalGroup(
            jd_superLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jd_superLayout.setVerticalGroup(
            jd_superLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));

        jb_agregarregular.setText("Agregar");
        jb_agregarregular.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_agregarregularMouseClicked(evt);
            }
        });

        jb_simular.setText("Simular");
        jb_simular.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_simularMouseClicked(evt);
            }
        });

        jl_regulares.setModel(new DefaultListModel());
        jl_regulares.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jl_regularesMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jl_regulares);

        jb_abrir2.setText("Abrir Archivo");
        jb_abrir2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_abrir2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(cb_regular, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jb_agregarregular)
                        .addGap(29, 29, 29)
                        .addComponent(jb_simular, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jb_abrir2))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(pgb_regular, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(cb_regular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jb_simular)
                        .addComponent(jb_abrir2))
                    .addComponent(jb_agregarregular))
                .addGap(18, 18, 18)
                .addComponent(pgb_regular, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jd_regularLayout = new javax.swing.GroupLayout(jd_regular.getContentPane());
        jd_regular.getContentPane().setLayout(jd_regularLayout);
        jd_regularLayout.setHorizontalGroup(
            jd_regularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jd_regularLayout.setVerticalGroup(
            jd_regularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Código");

        jb_guardarhack.setText("Agregar");
        jb_guardarhack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_guardarhackMouseClicked(evt);
            }
        });

        Riesgo.setForeground(new java.awt.Color(255, 255, 255));
        Riesgo.setText("Riesgo");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(Riesgo)
                                .addGap(18, 18, 18)
                                .addComponent(tf_riesgo, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(tf_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(jb_guardarhack)))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tf_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Riesgo)
                    .addComponent(tf_riesgo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(jb_guardarhack)
                .addContainerGap(67, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jd_agregarhackLayout = new javax.swing.GroupLayout(jd_agregarhack.getContentPane());
        jd_agregarhack.getContentPane().setLayout(jd_agregarhackLayout);
        jd_agregarhackLayout.setHorizontalGroup(
            jd_agregarhackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jd_agregarhackLayout.setVerticalGroup(
            jd_agregarhackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jb_hackregular.setText("Hackeo Regular");
        jb_hackregular.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_hackregularMouseClicked(evt);
            }
        });

        jb_superhack.setText("Súper Hackeo");
        jb_superhack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_superhackMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jb_superhack, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_hackregular))
                .addContainerGap(124, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addComponent(jb_hackregular)
                .addGap(18, 18, 18)
                .addComponent(jb_superhack)
                .addContainerGap(109, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jb_hackregularMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_hackregularMouseClicked
        tipohack = 1;
        jd_regular.setModal(true);
        jd_regular.pack();
        jd_regular.setLocationRelativeTo(this);
        jd_regular.setVisible(true);

    }//GEN-LAST:event_jb_hackregularMouseClicked

    private void jb_superhackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_superhackMouseClicked
        tipohack = 2;
        jd_super.setModal(true);
        jd_super.pack();
        jd_super.setLocationRelativeTo(this);
        jd_super.setVisible(true);

    }//GEN-LAST:event_jb_superhackMouseClicked

    private void jb_agregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_agregarMouseClicked
        jd_agregarhack.setModal(true);
        jd_agregarhack.pack();
        jd_agregarhack.setLocationRelativeTo(this);
        jd_agregarhack.setVisible(true);
    }//GEN-LAST:event_jb_agregarMouseClicked

    private void jb_guardarhackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_guardarhackMouseClicked
        if (tipohack == 1) {
            if (Integer.parseInt(tf_riesgo.getText()) < 1 || Integer.parseInt(tf_riesgo.getText()) > 5) {
                JOptionPane.showMessageDialog(jd_agregarhack, "No se agregó el hack, ingrese un riesgo mayor a 1 y menor a 5");

            } else {
                HackRegular hr = new HackRegular(tf_codigo.getText(), Integer.parseInt(tf_riesgo.getText()));
                hacksregulares.add(hr);
                DefaultListModel modelo = (DefaultListModel) jl_regulares.getModel();
                modelo.addElement(hr);
                jl_regulares.setModel(modelo);
//                adminRegular ar = new adminRegular("./hacksRegular.cbm");
//                ar.cargarArchivo();
//                ar.setHackregular(hr);
//                ar.escribirArchivo();
                Archivos a = new Archivos("./hacks.txt");
                a.cargarArchivo();
                a.setHackeos(hacksregulares);
                try {
                    a.escribirArchivo();
                } catch (IOException ex) {
                    Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
                }
                JOptionPane.showMessageDialog(this, "Hack guardado exitosamente");

            }
        } else {
            if (Integer.parseInt(tf_riesgo.getText()) < 6 || Integer.parseInt(tf_riesgo.getText()) > 10) {
                JOptionPane.showMessageDialog(jd_agregarhack, "No se agregó el hack, ingrese un riesgo mayor a 1 y menor a 5");
            } else {
                HackSuper hs = new HackSuper(tf_codigo.getText(), Integer.parseInt(tf_riesgo.getText()));
                hackssupers.add(hs);
                DefaultListModel modelo2 = (DefaultListModel) jl_super.getModel();
                modelo2.addElement(hs);
                jl_super.setModel(modelo2);
//                adminSuper ah = new adminSuper("./hacksSuper.cbm");
//                ah.cargarArchivo();
//                ah.setHackSuper(hs);
//                ah.escribirArchivo();
//                DefaultComboBoxModel modelo3 = new DefaultComboBoxModel(ah.getHacksSupers().toArray());
                Archivos a = new Archivos("./hackssupers.txt");
                a.cargarArchivo();
                a.setHackeos(hackssupers);
                try {
                    a.escribirArchivo();
                } catch (IOException ex) {
                    Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
                }

                JOptionPane.showMessageDialog(this, "Hack guardado exitosamente");
            }

        }


    }//GEN-LAST:event_jb_guardarhackMouseClicked

    private void jb_agregarregularMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_agregarregularMouseClicked
        jd_agregarhack.setModal(true);
        jd_agregarhack.pack();
        jd_agregarhack.setLocationRelativeTo(this);
        jd_agregarhack.setVisible(true);
    }//GEN-LAST:event_jb_agregarregularMouseClicked

    private void jb_simularMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_simularMouseClicked
        int caracteres = Integer.parseInt(JOptionPane.showInputDialog("Ingrese numero de caracteres con los que desea correr el hack"));
        if (jl_regulares.getSelectedIndex() >= 0) {
            int posicion = jl_regulares.getSelectedIndex();
            random(hacksregulares.get(posicion).getRiesgo());
            ah.setDuracion(caracteres * 2);
            pgb_regular.setMaximum(caracteres * 2);
            ah.setPgb_hack(pgb_regular);
            ah.start();
        }
    }//GEN-LAST:event_jb_simularMouseClicked

    private void jl_regularesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jl_regularesMouseClicked

    }//GEN-LAST:event_jl_regularesMouseClicked

    private void jb_simulacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_simulacionMouseClicked
        int numero = hackssupers.get(jl_super.getSelectedIndex()).getRiesgo();
        int caracteres2 = Integer.parseInt(JOptionPane.showInputDialog("Ingrese numero de caracteres con los que desea correr el hack"));
        random(numero);
        ah.setDuracion(caracteres2);
        pgb_super.setMaximum(caracteres2);
        ah.setPgb_hack(pgb_super);
        ah.start();
    }//GEN-LAST:event_jb_simulacionMouseClicked

    private void jl_superMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jl_superMouseClicked
        // TODO add your handling code here:
        pgb_regular.setValue(0);
        pgb_super.setValue(0);

    }//GEN-LAST:event_jl_superMouseClicked

    private void cb_hacksItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_hacksItemStateChanged
        if (evt.getStateChange() == 1) {
            HackSuper temp = (HackSuper) cb_hacks.getSelectedItem();
            if (temp != null) {
                jl_regulares.setModel(new DefaultListModel());

            }
        }
    }//GEN-LAST:event_cb_hacksItemStateChanged

    private void jb_abrir2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_abrir2MouseClicked
        Archivos ar = new Archivos("./hacks.txt");
        ar.cargarArchivo();
        DefaultListModel modelo = new DefaultListModel();
        jl_regulares.setModel(modelo);
        DefaultListModel modelo2 = (DefaultListModel) jl_regulares.getModel();
        for (int i = 0; i < ar.getHacks().size(); i++) {
            modelo2.addElement(ar.getHacks().get(i));
        }
        jl_regulares.setModel(modelo2);

    }//GEN-LAST:event_jb_abrir2MouseClicked

    private void jb_abrirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_abrirMouseClicked
        // TODO add your handling code here:
        Archivos ar = new Archivos("./hackssupers.txt");
        ar.cargarArchivo();
        DefaultListModel modelo = new DefaultListModel();
        jl_super.setModel(modelo);
        DefaultListModel modelo2 = (DefaultListModel) jl_super.getModel();
        for (int i = 0; i < ar.getHacks().size(); i++) {
            modelo2.addElement(ar.getHacks().get(i));
        }
        jl_regulares.setModel(modelo2);
    }//GEN-LAST:event_jb_abrirMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Riesgo;
    private javax.swing.JComboBox<String> cb_hacks;
    private javax.swing.JComboBox<String> cb_regular;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jb_abrir;
    private javax.swing.JButton jb_abrir2;
    private javax.swing.JButton jb_agregar;
    private javax.swing.JButton jb_agregarregular;
    private javax.swing.JButton jb_guardarhack;
    private javax.swing.JButton jb_hackregular;
    private javax.swing.JButton jb_simulacion;
    private javax.swing.JButton jb_simular;
    private javax.swing.JButton jb_superhack;
    private javax.swing.JDialog jd_agregarhack;
    private javax.swing.JDialog jd_regular;
    private javax.swing.JDialog jd_super;
    private javax.swing.JList<String> jl_regulares;
    private javax.swing.JList<String> jl_super;
    private javax.swing.JProgressBar pgb_regular;
    private javax.swing.JProgressBar pgb_super;
    private javax.swing.JTextField tf_codigo;
    private javax.swing.JTextField tf_riesgo;
    // End of variables declaration//GEN-END:variables
    ArrayList<Hackeo> hacksregulares = new ArrayList();
    ArrayList<Hackeo> hackssupers = new ArrayList();
    int tipohack;
    administrarHack ah;

    public void random(int numero) {
        Random r = new Random();
        int evaluacion = 1 + r.nextInt(10);
        if (numero == evaluacion) {
            JOptionPane.showMessageDialog(null, "You have been detected, deactivate the hack");
        }

    }
}
